import lineP from '../Img/lineP.jpeg'

const portfolios = [
    {
        id: 1,
        category:'ReactJS',
        link1: ,
        link2: ,
        icon1: ,
        icon2: ,
        image: ,
        title: 'Personal Website',
    },
    {
        id: 1,
        category: 'ReactJS',
        link1: ,
        link2: ,
        icon1: ,
        icon2: ,
        image: ,
        title: ,
    },{
        id: 1,
        category: 'AWS-CloudComputing',
        link1:'BestCryptoProducts.com' ,
        link2: 'https://github.com/Srashik/BestBitcoinProducts.git',
        icon1: ,
        icon2: ,
        image: ,
        title:'BestCryptoProducts.com' ,
    },
    {
        id: 1,
        category: 'ARM Processor',
        link1: 'https://github.com/USF-CS315-F21/project04-Srashik.git',
        link2: ,
        icon1: ,
        icon2: ,
        image: ,
        title: 'Arm Emulator' ,
    },
    {
        id: 1,
        category: 'Search Engine',
        link1: 'https://github.com/usf-cs212-spring2021/project-Srashik.git',
        link2:'' ,
        icon1: ,
        icon2: ,
        image: ,
        title:'Web-based Search Engine' ,
    },
    {
        id: 1,
        category: 'NFT Collection',
        link1: 'https://github.com/Srashik/GenerateNFT.git',
        link2:'https://opensea.io/assets/nine-lines-crazy-vibes?search[query]=nine%20lines',
        icon1: ,
        icon2: ,
        image: lineP,
        title: 'Nine Lines Project' ,
    },
    {
        id: 1,
        category: 'Xcode',
        link1: 'https://github.com/Srashik/AffordFinance.git',
        link2: ,
        icon1: ,
        icon2: ,
        image: ,
        title: 'Afford',
    },
    {
        id: 1,
        category: 'Data Structures and Algorithm' ,
        link1: 'https://github.com/Srashik/Data-Structures-and-Algorithms.git',
        link2:'' ,
        icon1: ,
        icon2: ,
        image: ,
        title: 'Data Structures and Algorithm Implementation',
    },
    {
        id: 1,
        category: 'Data Structures and Algorithm' ,
        link1: 'https://github.com/2020-cs112-USF-01/project2-tictactoe-Srashik.git',
        link2: ,
        icon1: ,
        icon2: ,
        image: ,
        title: 'Tic-Tac-Toe',
    },
    {
        id: 1,
        category: 'Data Structures and Algorithm' ,
        link1: 'https://github.com/Srashik/Data-Structures-and-Algorithms.git',
        link2: ,
        icon1: ,
        icon2: ,
        image: ,
        title: 'Sudoku',
    },
    
]

export default allportfolios
